/* ============================================================
   data.js — sample projects, i18n strings, helpers
   Plain JS (loaded via <script src>), exposes to window.
   ============================================================ */

// ---------- I18N ----------
const I18N = {
  pt: {
    locale: 'pt-BR',
    app_title: 'Shema — Gestão de Projetos',
    app_sub: 'Ecossistema de Projetos Internacionais · YWAM',
    headline_eyebrow: 'Vem ouvir.',
    headline: '<em>Assim na terra</em><br>como no céu.',
    headline_sub: 'Cada projeto é uma comunidade ouvindo a Palavra na própria voz. Acompanhe progresso, saúde e necessidades das equipes de campo.',
    nav_atlas: 'Atlas', nav_diario: 'Diário', nav_coral: 'Coral',
    btn_new: 'Novo Projeto', btn_export: 'Exportar', btn_import: 'Importar', btn_field: 'Receber Atualização',
    btn_intake: 'Link do líder',
    btn_reload: 'Recarregar', btn_reload_title: 'Recarregar dados da planilha (limpa o cache local)',
    confirm_reload: 'Recarregar os dados da planilha? Isso descarta alterações locais não exportadas e recarrega os 127 projetos do banco de dados.',
    btn_save: 'Salvar Projeto', btn_cancel: 'Cancelar', btn_delete: 'Excluir', btn_edit: 'Editar',
    btn_field_form: 'Enviar formulário ao campo',
    search_placeholder: 'Língua, equipe, parceiro...',
    filter_all: 'Todos',
    sb_team: 'Base', sb_objective: 'Objetivo', sb_status: 'Status', sb_health: 'Saúde', sb_financial: 'Recursos', sb_stale: 'Atualização',
    sb_country: 'País', sb_continent: 'Continente', sb_vitality: 'Vitalidade', sb_translation_type: 'Tipo de Tradução',
    sb_eten: 'ETEN', sb_progress_range: '% Progresso',
    sb_needs_section: 'Necessidades', sb_media: 'Mídia', sb_active_filters: 'Filtros ativos',
    sb_clear_all: 'Limpar tudo',
    sb_results_count: 'Mostrando', sb_results_of: 'de',
    sb_more_filters: 'Mais filtros', sb_less_filters: 'Menos filtros',
    sb_saved_views: 'Visões salvas',
    sb_save_view: 'Salvar esta visão',
    sb_save_view_prompt: 'Dê um nome a esta visão',
    sb_no_saved_views: 'Salve combinações de filtros que você usa toda semana.',
    sb_current_user: 'Estrategista Global ·',
    sb_coordinators: 'Coordenadores regionais',
    sb_regional_team: 'Time por região',
    sb_no_coordinator: '— a definir',
    role_coordinator: 'Administrador',
    role_obtlab: 'Operacional de Línguas',
    role_resource: 'Intercessor',
    role_coordinator_sub: 'Finanças e comunicação estratégica com as equipes de campo',
    role_obtlab_sub: 'Acompanha o progresso da tradução e demandas de treinamentos e workshops',
    role_resource_sub: 'Recebe pedidos de oração, ora e compartilha com a rede de intercessores',
    preset_mine: 'Pra mim',
    preset_mine_sub: 'Coordenados por você',
    preset_urgent: 'Pedem atenção', preset_urgent_sub: 'Saúde crítica · sem notícias · necessidades urgentes',
    preset_prayer: 'Em oração', preset_prayer_sub: 'Pedidos compartilhados',
    preset_celebrate: 'Celebrar', preset_celebrate_sub: 'Concluídos · orações respondidas',
    preset_recent: 'Recentes', preset_recent_sub: 'Atualizados em 30 dias',
    preset_eten: 'Lista ETEN', preset_eten_sub: 'Pertencem ao ETEN',
    preset_nomedia: 'Sem mídia', preset_nomedia_sub: 'Sem fotos ou vídeos',
    preset_progress: 'Em progresso', preset_progress_sub: 'Projetos ativos com avanço',
    preset_pending_needs: 'Pendências', preset_pending_needs_sub: 'Necessidades em aberto',
    preset_section: 'Atalhos', expand_filters: 'Filtros detalhados',
    continent_south_america: 'América do Sul',
    continent_north_america: 'América do Norte',
    continent_africa: 'África',
    continent_asia: 'Ásia',
    continent_oceania: 'Pacífico',
    continent_europe: 'Europa',
    continent_other: 'América Central',
    sb_country: 'País', sb_vitality: 'Vitalidade', sb_translation_type: 'Tipo de Tradução',
    sb_eten: 'ETEN', sb_progress_range: '% Progresso',
    sb_needs_section: 'Necessidades', sb_media: 'Mídia', sb_active_filters: 'Filtros ativos',
    sb_clear_all: 'Limpar tudo',
    range_0_25: '0–25%', range_25_50: '25–50%', range_50_75: '50–75%', range_75_100: '75–100%',
    bool_yes: 'Sim', bool_no: 'Não',
    needs_has_urgent: 'Com necessidade urgente',
    needs_in_prayer: 'Em rede de oração',
    media_has: 'Com fotos/vídeos',
    media_none: 'Sem mídia',
    stat_total: 'Línguas', stat_total_tail: 'em movimento',
    stat_teams: 'Bases', stat_teams_tail: 'YWAM/JOCUM',
    stat_progress: 'Em andamento', stat_progress_tail: 'com vida',
    stat_completed: 'Concluídos', stat_completed_tail: 'celebrados',
    stat_urgent: 'Urgentes', stat_urgent_tail: 'pedem oração',
    stat_stale: 'Sem notícias', stat_stale_tail: 'há mais de 60 dias',
    sort_deadline: 'Prazo', sort_name: 'Língua (A-Z)', sort_progress: 'Progresso', sort_team: 'Equipe', sort_health: 'Saúde',
    results_one: 'projeto', results_many: 'projetos', results_of: 'de',
    empty_title: 'Nenhum projeto por aqui.',
    empty_sub: 'Ajuste os filtros ou registre o primeiro projeto.',
    sec_id: 'Identidade',
    sec_team: 'Equipe',
    sec_objective: 'Objetivo',
    sec_progress: 'Progresso',
    sec_health: 'Saúde da Equipe',
    sec_needs: 'Necessidades',
    sec_notes: 'Notas',
    sec_materials: 'Materiais Traduzidos',
    f_materials_hint: 'Importe os áudios e textos já traduzidos. Indique o tipo e o escopo de cada material.',
    mat_kind_text: 'Texto traduzido', mat_kind_audio: 'Áudio traduzido', mat_kind_video: 'Vídeo traduzido',
    mat_scope: 'Escopo (ex: Evangelho de João, cap. 1–3)',
    mat_import: 'Importar arquivo', mat_replace: 'Trocar arquivo', mat_no_file: 'Nenhum arquivo importado', mat_add: 'Adicionar material', mat_open: 'Abrir / Baixar',
    mat_or_link: 'ou link', mat_link_ph: 'Cole um link (Drive, nuvem…)', mat_open_link: 'Abrir link', mat_has_link: 'Link externo',
    sec_financial: 'Recursos Financeiros',
    sec_media: 'Fotos / Vídeos',
    f_media_intro: 'Compartilhe momentos do trabalho de campo — fotos da equipe, cópia do material traduzido, eventos de entrega, treinamentos.',
    media_auth_intro: 'Autorização de uso: marque cada foto/vídeo que a equipe autoriza compartilhar publicamente. Sem a marcação, o item fica restrito.',
    media_auth_label: 'Autorizo compartilhar', media_auth_yes: 'Uso autorizado', media_auth_no: 'Uso restrito',
    f_media_photo_label: 'Foto',
    f_media_caption: 'Legenda',
    f_media_video_label: 'Link do vídeo (YouTube, Vimeo, etc.)',
    f_media_add_video: '+ Adicionar vídeo',
    f_media_videos_title: 'Vídeos',
    f_media_photos_title: 'Fotos',
    f_media_drop_hint: 'Arraste uma foto aqui',
    f_leader_contact: 'Contato do Líder (email/WhatsApp)',
    f_mentor_contact: 'Contato do Mentor (email/WhatsApp)',
    f_in_eten: 'Língua na lista do ETEN',
    f_project_status: 'Status do Projeto',
    project_status_active: 'Em andamento',
    project_status_paused: 'Paralisado / Inativo',
    project_status_planned: 'Em planejamento',
    progress_books_title: 'Progresso por Livro da Bíblia',
    progress_books_hint: 'Marque os livros em tradução e atualize quantos capítulos já estão em cada fase.',
    progress_stories_title: 'Progresso por História',
    progress_stories_hint: 'Adicione cada história e atualize seu progresso.',
    story_location_ph: 'Local de coleta (aldeia, comunidade, estúdio…)',
    story_audio_hours: 'Horas de áudio',
    story_st_planned: 'A gravar', story_st_recording: 'Em gravação', story_st_recorded: 'Gravada',
    story_ai: 'IA assistida',
    f_stories_translated: 'Histórias traduzidas',
    f_stories_translated_hint: 'Total de histórias já concluídas',
    f_rv_audio_hours: 'Horas de áudio · Ready Vessels',
    f_rv_audio_hours_hint: 'Horas de áudio já gravadas',
    progress_other_title: 'Outras Unidades',
    btn_add_book: '+ Adicionar livro',
    btn_add_story: '+ Adicionar história',
    btn_add_unit: '+ Adicionar unidade',
    col_book: 'Livro', col_story: 'História', col_unit: 'Unidade',
    col_chapters: 'Caps',
    col_translated: 'Traduzido', col_checked: 'Comunidade', col_approved: 'Aprovado',
    d_target: 'Língua-alvo', d_bridge: 'Língua ponte', d_vitality: 'Vitalidade', d_speakers: 'Falantes',
    d_location: 'Localização', d_type: 'Tipo de tradução', d_financial: 'Recursos financeiros',
    d_facilitators: 'Equipe / Base', d_ywam: 'Base YWAM/JOCUM', d_leader: 'Líder', d_mentor: 'Mentor', d_regional_coord: 'Administrador',
    f_regional_coord: 'Administrador', placeholder_regional_coord: 'Administrador — finanças e comunicação',
    f_obtlab_person: 'Operacional de Línguas', placeholder_obtlab: 'Operacional de Línguas — progresso e treinamentos',
    f_resource_person: 'Intercessor', placeholder_resource: 'Intercessor — oração e rede',
    d_obtlab_person: 'Operacional de Línguas', d_resource_person: 'Intercessor',
    detail_team_section: 'Time regional',
    nav_projetos: 'Projetos', nav_ritmo: 'Ritmo', nav_eten: 'ETEN', nav_oracao: 'Oração', nav_formularios: 'Formulários', nav_equipe: 'Equipe', nav_intercessores: 'Intercessores',
    int_eyebrow: 'Rede de intercessores',
    int_title: 'Quem ora pelo campo',
    int_lead: 'Cadastre os intercessores e grupos pelo mundo. Envie os pedidos de oração do mural diretamente a cada um, por WhatsApp ou e-mail.',
    int_name: 'Nome', int_name_ph: 'Nome do intercessor ou grupo',
    int_country: 'País', int_country_ph: 'Ex: Brasil',
    int_contact: 'Contato', int_contact_ph: 'WhatsApp ou e-mail',
    int_add: 'Adicionar',
    int_registered: 'cadastrados', int_broadcast: 'Enviar mural a todos',
    int_send: 'Enviar pedidos', int_send_wa: 'WhatsApp', int_send_mail: 'E-mail', int_copy: 'Copiar',
    int_empty: 'Nenhum intercessor cadastrado ainda. Adicione nome, país e contato acima.',
    int_footnote: 'Os pedidos enviados vêm do Mural de Oração — apenas os autorizados a compartilhar pelas equipes.',
    int_email_subject: 'Pedidos de oração · Shema',
    equipe_eyebrow: 'Organograma · Time por região',
    equipe_title: 'A equipe de cada região',
    equipe_lead: 'Adicione e atualize os nomes dos três papéis de cada região. As mudanças aparecem na barra lateral, nas reuniões e nos projetos.',
    equipe_global: 'Articulador Geral',
    equipe_placeholder: 'Nome da pessoa',
    equipe_save: 'Salvar alterações', equipe_saved: '✓ Salvo', equipe_hint: 'Edite os nomes e clique em salvar.',
    forms_eyebrow: 'Formulários do campo · Onde encontrá-los',
    forms_title: 'Os dois formulários',
    forms_lead: 'Aqui você gera e localiza os dois formulários que as equipes preenchem. As respostas voltam pela aba “Receber Atualização” e geram notificações automáticas.',
    forms_pick_project: 'Escolha o projeto',
    forms_generate: 'Gerar formulário (.html)',
    forms_open_health: 'Abrir avaliação no app',
    forms_footnote: 'O Pulso Mensal é um arquivo que o líder preenche no celular e devolve em .json. A Avaliação de Saúde abre dentro do app, conduzida pelo Facilitador durante a reunião.',
    forms_received_title: 'Formulários recebidos', forms_refresh: 'Atualizar', forms_import: 'Importar formulário',
    forms_received_empty: 'Nenhum formulário arquivado ainda. Ao importar um .json em “Receber Atualização” (ou aqui), o formulário preenchido fica guardado para você baixar quando quiser.',
    forms_tag_pulse: 'Pulso', forms_tag_health: 'Saúde', forms_download: 'Baixar',
    oracao_eyebrow: 'Mural de Oração · Rede de intercessores',
    oracao_title: 'Pedidos de oração do campo',
    oracao_lead: 'Todos os pedidos de oração — vindos do Pulso Mensal e das Avaliações de Saúde — reunidos aqui para compartilhar com grupos de intercessores no mundo todo.',
    oracao_total: 'Pedidos reunidos', oracao_regions: 'Regiões', oracao_answered: 'Respondidas',
    oracao_all: 'Todas', oracao_share: 'WhatsApp', oracao_db: 'Baixar banco de dados',
    oracao_answered_tag: 'Respondida', oracao_empty: 'Nenhum pedido de oração ainda. Quando as equipes enviarem os formulários, os pedidos aparecem aqui.',
    oracao_footnote: 'TXT para compartilhar com grupos · CSV e JSON para o banco de dados de intercessão. Os pedidos vêm dos dois formulários (Pulso Mensal e Avaliação de Saúde).',
    oracao_sub_mural: 'Mural de oração', oracao_sub_rede: 'Rede de intercessores',
    eten_eyebrow: 'Relatório anual · Círculo de Recursos',
    eten_title: 'Créditos ETEN',
    eten_lead: 'O ETEN financia a maior parte dos recursos do Shema. A cada ano relatamos quantos capítulos cada projeto avançou. Cada capítulo avançado vale 1 crédito — e o total de créditos corresponde aos recursos do próximo ciclo. Apenas projetos na lista do ETEN são contabilizados.',
    eten_report_year: 'Ano do relatório',
    eten_total_credits: 'Créditos no ano', eten_credits_note: '1 capítulo avançado = 1 crédito',
    eten_listed: 'Projetos no ETEN', eten_listed_sub: 'na lista de financiamento',
    eten_advancing: 'Com avanço', eten_advancing_sub: 'tiveram capítulos novos em',
    eten_report_for: 'Relatório do ano', eten_export_csv: 'Baixar CSV', eten_gen_report: 'Gerar relatório (PDF)',
    eten_col_project: 'Projeto', eten_col_start: 'Início', eten_col_end: 'Fim', eten_col_credits: 'Créditos',
    eten_total: 'Total', eten_empty: 'Nenhum projeto marcado na lista do ETEN. Marque "Língua na lista do ETEN" no formulário de cada projeto.',
    eten_footnote: 'Os créditos são calculados automaticamente: capítulos traduzidos ao fim do ano menos os do fim do ano anterior, por projeto listado no ETEN. Atualize o progresso de cada projeto para refletir no relatório.',
    ritmo_eyebrow: 'Cascata de escuta',
    ritmo_title: 'O ritmo do ecossistema',
    ritmo_lead: 'Shema significa "ouça". Cada reunião é uma etapa dessa escuta — a informação flui do campo até a liderança, e o cuidado flui de volta. Os formulários alimentam as reuniões; as reuniões alimentam as decisões.',
    ritmo_monthly: 'Mensal', ritmo_quarterly: 'Trimestral', ritmo_annual: 'Anual',
    ritmo_all_ecosystem: 'Todo o ecossistema',
    ritmo_m1_title: 'Pulso Mensal', ritmo_m1_desc: 'O Operacional de Línguas revisa, todo mês, os pulsos das equipes da região e decide o que escalar para a reunião trimestral.',
    ritmo_m2_title: 'Cuidado de campo', ritmo_m2_desc: 'O Operacional de Línguas do time regional conduz a Avaliação de Saúde, trimestral, com cada equipe de tradução da região.',
    ritmo_m3_title: 'Estratégia regional', ritmo_m3_desc: 'A Estrategista Global se reúne, a cada trimestre, com o Operacional de Línguas e o Administrador de cada região para alinhar progresso, recursos e o plano do trimestre.',
    ritmo_m6_title: 'Pulso de oração', ritmo_m6_desc: 'O Intercessor compila os pedidos de oração do mês e os compartilha com a rede de intercessores.',
    ritmo_m7_title: 'Repasse de recursos', ritmo_m7_desc: 'A Estrategista Global e o Administrador levam as necessidades financeiras acumuladas das regiões ao Círculo de Recursos, a cada trimestre.',
    ritmo_m4_title: 'Governança', ritmo_m4_desc: 'O Estrategista Global e a liderança Shema revisam a saúde de todo o ecossistema e a direção estratégica.',
    ritmo_m5_title: 'Celebração anual', ritmo_m5_desc: 'Todos juntos: retrospectiva do ano, orações respondidas, marcos de tradução entregues.',
    role_coordinator: 'Administrador', role_obtlab: 'Operacional de Línguas', role_resource: 'Intercessor',
    ritmo_role_supervisor: 'Estrategista Global', ritmo_role_leadership: 'Liderança Shema',
    ritmo_role_teams: 'Equipes de tradução', ritmo_role_everyone: 'Todos', ritmo_role_resourcecircle: 'Círculo de Recursos',
    ritmo_feeds: 'Alimentada por:', 
    ritmo_feed_pulso: 'Pulsos mensais das equipes', ritmo_feed_health: 'Avaliações de Saúde (4 dimensões)',
    ritmo_feed_trends: 'Tendências do trimestre + necessidades acumuladas', ritmo_feed_rollup: 'Roll-up de saúde de todas as regiões',
    ritmo_feed_year: 'Marcos e testemunhos do ano', ritmo_feed_prayer: 'Pedidos de oração do mês', ritmo_feed_resources: 'Necessidades financeiras das regiões',
    ritmo_st_done: 'Em dia', ritmo_st_pending: 'A fazer', ritmo_st_overdue: 'Atrasada', ritmo_st_new: 'A iniciar',
    ritmo_last: 'Última', ritmo_next: 'Próxima', ritmo_register: 'Registrar reunião',
    ritmo_done_this: 'Realizada em', ritmo_undo: 'Desfazer', ritmo_save: 'Salvar',
    ritmo_date: 'Data', ritmo_notes: 'Notas', ritmo_notes_ph: 'Decisões, encaminhamentos (opcional)',
    ritmo_readiness: 'Equipes que já reportaram neste período', ritmo_reported: 'reportaram',
    d_facilitator_person: 'Facilitador',
    d_translators: 'Tradutores', d_reviewers: 'Revisores', d_partner: 'Parceiro', d_contact: 'Contato',
    d_objective: 'Tipo de projeto', d_total: 'Total planejado', d_scope: 'Escopo',
    d_portion: 'Porção em tradução',
    d_start: 'Início', d_deadline: 'Prazo',
    d_p_translated: 'Já traduzido', d_p_community: 'Checado na comunidade', d_p_approved: 'Aprovado pelo mentor',
    d_emotional: 'Emocional', d_relational: 'Relacional', d_spiritual: 'Espiritual', d_physical: 'Física',
    d_last_assessment: 'Última avaliação', d_assessor: 'Avaliada por',
    d_notes: 'Notas', d_prayer: 'Pedidos de oração', d_pastoral: 'Intervenção pastoral',
    d_no_needs: 'Sem necessidades específicas registradas.',
    d_history_toggle: 'Histórico de progresso',
    d_history_records: 'registros', d_history_record: 'registro',
    d_history_initial: '(registro inicial)',
    d_history_translated: 'Traduzido:', d_history_approved: 'Aprovado:', d_history_community: 'Comunidade:',
    health_good: 'Boa', health_attention: 'Atenção', health_critical: 'Crítica', health_na: 'N/A',
    vit_vital: 'Vital', vit_vulnerable: 'Vulnerável', vit_threatened: 'Ameaçada',
    vit_severely: 'Seriamente ameaçada', vit_critical: 'Em situação crítica', vit_extinct: 'Extinta', vit_na: 'Não avaliado',
    status_not_started: 'Não iniciado', status_in_progress: 'Em andamento', status_final: 'Fase final', status_completed: 'Concluído',
    status_paused: 'Pausado', status_canceled: 'Cancelado', status_planned: 'Planejado', status_unknown: 'Sem informação',
    stale_uptodate: 'Em dia', stale_attention: 'Sem notícias 60+ dias', stale_critical: 'Crítico 120+ dias',
    days_overdue: 'd em atraso', days_remaining: 'd restantes',
    deadline_left: 'Faltam',
    stale_warn_title: 'Sem atualização recente.', stale_warn_text: 'Sem notícias do campo há',
    stale_crit_title: 'Equipe sem contato.', stale_crit_text: 'Sem registro de progresso há',
    days: 'dias',
    nav_id: '1 Identificação', nav_eq: '2 Equipe', nav_obj: '3 Objetivo', nav_prog: '4 Progresso',
    nav_health: '5 Saúde', nav_needs: '6 Necessidades', nav_notes: '7 Notas',
    f_lang_name: 'Nome da Língua', f_lang_code: 'Código ISO', f_bridge: 'Língua Ponte',
    f_vitality: 'Vitalidade', f_location: 'País / Região / Localização',
    f_location2: 'País / Região adicional', placeholder_location2: 'Outro país onde a língua é falada (opcional)',
    f_speakers: 'Número de falantes', f_translation_type: 'Tipo de Tradução',
    f_sensitive: 'País sensível para divulgação da Bíblia',
    f_sensitive_hint: 'Marque se a divulgação pública pode pôr a equipe em risco.',
    d_sensitive_tag: 'País sensível', sb_sensitive: 'País sensível',
    sensitive_yes: 'Sensível', sensitive_no: 'Aberto',
    f_financial: 'Recursos Financeiros',
    f_facilitators: 'Base / Equipe', f_ywam: 'Base YWAM/JOCUM', f_leader: 'Líder da Equipe',
    f_mentor: 'Mentor', f_translators: 'Tradutores', f_reviewers: 'Revisores Técnicos',
    f_partner: 'Organização Parceira', f_contact: 'Contato / Email / WhatsApp',
    f_obj: 'Escopo da tradução', f_total_planned: 'Total Planejado', f_unit_type: 'Unidade',
    f_phases: 'Etapas do projeto', f_phases_hint: 'Divida o projeto por períodos. Cada etapa tem meta e prazo próprios.',
    f_phase_n: 'Etapa', f_phase_scope: 'Meta da etapa (ex: Evangelho de João)', f_phase_add: 'Adicionar etapa',
    d_phases: 'Etapas',
    f_scope: 'Escopo (livros, capítulos…)',
    f_translated: '1. Já traduzido', f_community: '2. Checagem na comunidade',
    f_approved: '3. Aprovado pelo mentor', f_start: 'Data de início', f_deadline: 'Prazo de entrega',
    f_emotional: 'Emocional', f_relational: 'Relacional', f_spiritual: 'Espiritual', f_physical: 'Física',
    f_assessment_date: 'Data da última avaliação', f_assessor: 'Avaliada por',
    f_health_notes: 'Notas sobre a saúde', f_prayer: 'Pedidos de oração',
    f_pastoral: 'Precisa de intervenção pastoral?', f_pastoral_who: 'Quem fará?',
    f_need_financial: 'Apoio financeiro', f_need_training: 'Treinamento', f_need_equipment: 'Equipamento',
    need_cat_financial: '💰 Financeiro', need_cat_training: '🎓 Treinamento', need_cat_equipment: '💻 Equipamento',
    need_cat_volunteers: '🤝 Voluntários', need_cat_material: '📚 Material didático',
    need_cat_security: '🛡️ Segurança', need_cat_connectivity: '📡 Conectividade',
    need_cat_logistics: '🚗 Transporte / Logística', need_cat_documentation: '📑 Documentação',
    need_urgency_label: 'Urgência',
    need_urgency_low: 'Baixa', need_urgency_medium: 'Média', need_urgency_high: 'Urgente',
    need_status_label: 'Status',
    need_status_open: 'Aberto', need_status_inprogress: 'Em curso', need_status_fulfilled: 'Atendido',
    need_estimated_value: 'Valor estimado',
    need_deadline: 'Prazo',
    need_description: 'Descrição',
    need_fulfilled_by: 'Atendido por',
    need_fulfilled_date: 'Data de atendimento',
    need_prayer_shared: 'Compartilhado em rede de oração',
    need_prayer_answered: 'Respondido em oração',
    need_add_item: '+ Adicionar necessidade',
    needs_export: 'Baixar dados',
    need_submitted_by: 'Preenchido por', need_submitted_at: 'Preenchido em',
    need_quick_categories: 'Categorias rápidas (com necessidade ativa)',
    need_items_title: 'Lista de pedidos',
    f_needs_notes: 'Observações gerais',
    f_notes: 'Notas livres',
    placeholder_lang: 'Ex: Yanomami',
    placeholder_iso: 'Ex: ymv',
    placeholder_bridge: 'Ex: Português',
    placeholder_location: 'Ex: Roraima, Brasil — TI Yanomami',
    placeholder_facilitators: 'Ex: Equipe Norte',
    placeholder_leader: 'Nome do líder',
    placeholder_translators: 'Separados por vírgula',
    progress_tip: 'Mudanças nos números abaixo são salvas no histórico automaticamente.',
    sim: 'Sim', nao: 'Não',
    unit_books: 'Livros', unit_chapters: 'Capítulos', unit_verses: 'Versículos',
    unit_pages: 'Páginas', unit_stories: 'Histórias', unit_other: 'Outro',
    proj_nt: 'Novo Testamento', proj_ot: 'Antigo Testamento', proj_complete: 'Bíblia Completa',
    proj_books: 'Livros Específicos', proj_chapters: 'Capítulos', proj_stories: 'Histórias',
    proj_jesus: 'Filme Jesus', proj_written: 'Tradução escrita', proj_other: 'Outro',
    proj_obt: 'OBT', proj_omt: 'OMT', proj_obtomt: 'OBT/OMT', proj_sign: 'Língua de Sinais', proj_ready: 'Ready Vessels',
    fin_seed: 'Seed Company', fin_global: 'Global Partnerships', fin_eten: 'OBT TABLE - ETEN', fin_innov: 'Innovation Lab',
    toast_saved: 'Projeto salvo.', toast_deleted: 'Projeto removido.',
    toast_exported: 'Dados exportados.', toast_imported: 'projetos importados.',
    toast_field_generated: 'Formulário do campo gerado — envie ao time.',
    toast_field_received: 'Atualização do campo aplicada.',
    toast_field_invalid: 'Arquivo de atualização inválido.',
    toast_obj_required: 'Selecione ao menos um tipo de projeto.',
    confirm_delete: 'Excluir este projeto? Esta ação não pode ser desfeita.',
    confirm_import: 'Importar substituirá os projetos atuais. Continuar?',
    modal_new: 'Novo Projeto', modal_edit: 'Editar Projeto',
    tweaks_title: 'Variações',
    tweaks_metaphor: 'Metáfora visual',
    tweaks_metaphor_sub: 'Como você quer ver os projetos hoje?',
    tweaks_density: 'Densidade',
    tweaks_accent: 'Cor de destaque',
    tweaks_show_photos: 'Mostrar fotografia hero',
    field_title: 'Formulário do Campo',
    field_form_progress: '📊 Progresso',
    field_form_health: '❤️ Saúde da Equipe',
    field_form_needs: '🤝 Necessidades',
    field_form_media: '📸 Mídia & Testemunhos',
    field_form_full: '📋 Atualização Completa',
    field_form_choose: 'Enviar formulário…',
    field_sub: 'Preencha e baixe o arquivo para retornar à coordenação.',
    field_section_progress: 'Progresso',
    field_section_needs: 'Necessidades',
    field_section_pastoral: 'Apoio Pastoral',
    field_section_notes: 'Notas',
    field_pastoral_question: 'A equipe precisa de apoio pastoral neste momento?',
    field_pastoral_details: 'Descreva a situação (opcional)',
    field_prayer_label: 'Pedidos de oração',
    field_label_project: 'Projeto:', field_label_team: 'Equipe:', field_label_mentor: 'Mentor:',
    field_label_date: 'Data:',
    field_your_name: 'Seu nome (quem está reportando)',
    field_save_btn: 'Baixar atualização',
    field_saved: 'Atualização gerada. Envie o arquivo ao coordenador.',
    field_instructions: 'Como usar:',
    field_instr_1: 'Atualize os números abaixo conforme o progresso real desde a última checagem.',
    field_instr_2: 'Marque as necessidades atuais (financeira, treinamento, equipamento).',
    field_instr_3: 'Acrescente notas, pedidos de oração ou contexto recente.',
    field_instr_4: 'Clique em "Baixar atualização" e envie o arquivo .json à coordenação.',
  },
  en: {
    locale: 'en-US',
    app_title: 'Shema — Project Management',
    app_sub: 'International Projects Ecosystem · YWAM',
    headline_eyebrow: 'Come listen.',
    headline: '<em>On earth</em><br>as it is in heaven.',
    headline_sub: 'Every project is a community hearing the Word in its own voice. Track progress, health and field-team needs.',
    nav_atlas: 'Atlas', nav_diario: 'Journal', nav_coral: 'Reef',
    btn_new: 'New Project', btn_export: 'Export', btn_import: 'Import', btn_field: 'Receive Update',
    btn_intake: 'Leader link',
    btn_reload: 'Reload', btn_reload_title: 'Reload data from the spreadsheet (clears local cache)',
    confirm_reload: 'Reload data from the spreadsheet? This discards unexported local changes and reloads the 127 projects from the database.',
    btn_save: 'Save Project', btn_cancel: 'Cancel', btn_delete: 'Delete', btn_edit: 'Edit',
    btn_field_form: 'Send form to the field',
    search_placeholder: 'Language, team, partner...',
    filter_all: 'All',
    sb_team: 'Base', sb_objective: 'Objective', sb_status: 'Status', sb_health: 'Health', sb_financial: 'Funding', sb_stale: 'Updates',
    sb_country: 'Country', sb_continent: 'Continent', sb_vitality: 'Vitality', sb_translation_type: 'Translation Type',
    sb_eten: 'ETEN', sb_progress_range: '% Progress',
    sb_needs_section: 'Needs', sb_media: 'Media', sb_active_filters: 'Active filters',
    sb_clear_all: 'Clear all',
    sb_results_count: 'Showing', sb_results_of: 'of',
    sb_more_filters: 'More filters', sb_less_filters: 'Fewer filters',
    sb_saved_views: 'Saved views',
    sb_save_view: 'Save this view',
    sb_save_view_prompt: 'Name this view',
    sb_no_saved_views: 'Save filter combos you use every week.',
    sb_current_user: 'Global Articulator ·',
    sb_coordinators: 'Regional coordinators',
    sb_regional_team: 'Team by region',
    sb_no_coordinator: '— to be set',
    role_coordinator: 'Administrator',
    role_obtlab: 'Language Operations',
    role_resource: 'Intercessor',
    role_coordinator_sub: 'Finances and strategic communication with field teams',
    role_obtlab_sub: 'Tracks translation progress and training/workshop needs',
    role_resource_sub: 'Receives prayer requests, prays and shares with the intercessor network',
    preset_mine: 'For me',
    preset_mine_sub: 'You coordinate these',
    preset_urgent: 'Need attention', preset_urgent_sub: 'Critical health · no news · urgent needs',
    preset_prayer: 'In prayer', preset_prayer_sub: 'Shared requests',
    preset_celebrate: 'Celebrate', preset_celebrate_sub: 'Completed · answered prayers',
    preset_recent: 'Recent', preset_recent_sub: 'Updated in 30 days',
    preset_eten: 'ETEN list', preset_eten_sub: 'Belongs to ETEN',
    preset_nomedia: 'No media', preset_nomedia_sub: 'No photos or videos',
    preset_progress: 'In progress', preset_progress_sub: 'Active projects with traction',
    preset_pending_needs: 'Pending', preset_pending_needs_sub: 'Open needs',
    preset_section: 'Shortcuts', expand_filters: 'Detailed filters',
    continent_south_america: 'South America',
    continent_north_america: 'North America',
    continent_africa: 'Africa',
    continent_asia: 'Asia',
    continent_oceania: 'Pacific',
    continent_europe: 'Europe',
    continent_other: 'Central America',
    range_0_25: '0–25%', range_25_50: '25–50%', range_50_75: '50–75%', range_75_100: '75–100%',
    bool_yes: 'Yes', bool_no: 'No',
    needs_has_urgent: 'Has urgent need',
    needs_in_prayer: 'In prayer network',
    media_has: 'With photos/videos',
    media_none: 'No media',
    stat_total: 'Languages', stat_total_tail: 'in motion',
    stat_teams: 'Bases', stat_teams_tail: 'YWAM/JOCUM',
    stat_progress: 'In progress', stat_progress_tail: 'alive',
    stat_completed: 'Completed', stat_completed_tail: 'celebrated',
    stat_urgent: 'Urgent', stat_urgent_tail: 'need prayer',
    stat_stale: 'No news', stat_stale_tail: 'for 60+ days',
    sort_deadline: 'Deadline', sort_name: 'Language (A-Z)', sort_progress: 'Progress', sort_team: 'Team', sort_health: 'Health',
    results_one: 'project', results_many: 'projects', results_of: 'of',
    empty_title: 'Nothing here yet.',
    empty_sub: 'Adjust filters or register the first project.',
    sec_id: 'Identity',
    sec_team: 'Team',
    sec_objective: 'Objective',
    sec_progress: 'Progress',
    sec_health: 'Team Health',
    sec_needs: 'Needs',
    sec_notes: 'Notes',
    sec_materials: 'Translated Materials',
    f_materials_hint: 'Import the already-translated audio and text. Indicate the type and scope of each material.',
    mat_kind_text: 'Translated text', mat_kind_audio: 'Translated audio', mat_kind_video: 'Translated video',
    mat_scope: 'Scope (e.g. Gospel of John, ch. 1–3)',
    mat_import: 'Import file', mat_replace: 'Replace file', mat_no_file: 'No file imported', mat_add: 'Add material', mat_open: 'Open / Download',
    mat_or_link: 'or link', mat_link_ph: 'Paste a link (Drive, cloud…)', mat_open_link: 'Open link', mat_has_link: 'External link',
    sec_financial: 'Financial Resources',
    sec_media: 'Photos / Videos',
    f_media_intro: 'Share field-work moments — team photos, the translated material, dedication events, trainings.',
    media_auth_intro: 'Usage authorization: check each photo/video the team authorizes for public sharing. Without the check, the item stays restricted.',
    media_auth_label: 'I authorize sharing', media_auth_yes: 'Sharing authorized', media_auth_no: 'Restricted use',
    f_media_photo_label: 'Photo',
    f_media_caption: 'Caption',
    f_media_video_label: 'Video link (YouTube, Vimeo, etc.)',
    f_media_add_video: '+ Add video',
    f_media_videos_title: 'Videos',
    f_media_photos_title: 'Photos',
    f_media_drop_hint: 'Drop a photo here',
    f_leader_contact: 'Leader contact (email/WhatsApp)',
    f_mentor_contact: 'Mentor contact (email/WhatsApp)',
    f_in_eten: 'Language on ETEN list',
    f_project_status: 'Project Status',
    project_status_active: 'In progress',
    project_status_paused: 'Paused / Inactive',
    project_status_planned: 'Planning',
    progress_books_title: 'Progress by Bible Book',
    progress_books_hint: 'Mark the books in translation and update how many chapters are at each stage.',
    progress_stories_title: 'Progress by Story',
    progress_stories_hint: 'Add each story and track its progress.',
    story_location_ph: 'Collection site (village, community, studio…)',
    story_audio_hours: 'Audio hours',
    story_st_planned: 'To record', story_st_recording: 'Recording', story_st_recorded: 'Recorded',
    story_ai: 'AI assisted',
    f_stories_translated: 'Stories translated',
    f_stories_translated_hint: 'Total stories completed',
    f_rv_audio_hours: 'Audio hours · Ready Vessels',
    f_rv_audio_hours_hint: 'Audio hours recorded so far',
    progress_other_title: 'Other Units',
    btn_add_book: '+ Add book',
    btn_add_story: '+ Add story',
    btn_add_unit: '+ Add unit',
    col_book: 'Book', col_story: 'Story', col_unit: 'Unit',
    col_chapters: 'Chs',
    col_translated: 'Translated', col_checked: 'Community', col_approved: 'Approved',
    d_target: 'Target language', d_bridge: 'Bridge language', d_vitality: 'Vitality', d_speakers: 'Speakers',
    d_location: 'Location', d_type: 'Translation type', d_financial: 'Funding',
    d_facilitators: 'Team / Base', d_ywam: 'YWAM/JOCUM base', d_leader: 'Leader', d_mentor: 'Mentor', d_regional_coord: 'Regional Host',
    f_regional_coord: 'Regional Host', placeholder_regional_coord: 'Regional host — lives in the region',
    f_obtlab_person: 'International Project Facilitator', placeholder_obtlab: 'International Project Facilitator (internal team)',
    f_resource_person: 'Financial Resource Mobilizer', placeholder_resource: 'Financial Resource Mobilizer for the region',
    d_obtlab_person: 'International Project Facilitator', d_resource_person: 'Financial Resource Mobilizer',
    detail_team_section: 'Regional team',
    nav_projetos: 'Projects', nav_ritmo: 'Rhythm', nav_eten: 'ETEN', nav_oracao: 'Prayer', nav_formularios: 'Forms', nav_equipe: 'Team', nav_intercessores: 'Intercessors',
    int_eyebrow: 'Intercessor network',
    int_title: 'Who prays for the field',
    int_lead: 'Register intercessors and groups worldwide. Send the prayer wall requests to each one directly, by WhatsApp or email.',
    int_name: 'Name', int_name_ph: 'Intercessor or group name',
    int_country: 'Country', int_country_ph: 'e.g. Brazil',
    int_contact: 'Contact', int_contact_ph: 'WhatsApp or email',
    int_add: 'Add',
    int_registered: 'registered', int_broadcast: 'Send wall to all',
    int_send: 'Send requests', int_send_wa: 'WhatsApp', int_send_mail: 'Email', int_copy: 'Copy',
    int_empty: 'No intercessors registered yet. Add name, country and contact above.',
    int_footnote: 'Sent requests come from the Prayer Wall — only those teams authorized to share.',
    int_email_subject: 'Prayer requests · Shema',
    equipe_eyebrow: 'Org chart · Team by region',
    equipe_title: 'Each region\u2019s team',
    equipe_lead: 'Add and update the names of the three roles in each region. Changes appear in the sidebar, meetings and projects.',
    equipe_global: 'Global Articulator',
    equipe_placeholder: 'Person\u2019s name',
    equipe_save: 'Save changes', equipe_saved: '✓ Saved', equipe_hint: 'Edit the names and click save.',
    forms_eyebrow: 'Field forms · Where to find them',
    forms_title: 'The two forms',
    forms_lead: 'Here you generate and locate the two forms teams fill in. Responses return via the “Receive Update” tab and trigger automatic notifications.',
    forms_pick_project: 'Choose the project',
    forms_generate: 'Generate form (.html)',
    forms_open_health: 'Open assessment in app',
    forms_footnote: 'The Monthly Pulse is a file the leader fills on the phone and returns as .json. The Health Assessment opens inside the app, run by the Facilitator during the meeting.',
    forms_received_title: 'Forms received', forms_refresh: 'Refresh', forms_import: 'Import form',
    forms_received_empty: 'No forms archived yet. When you import a .json in “Receive Update” (or here), the filled form is kept for you to download anytime.',
    forms_tag_pulse: 'Pulse', forms_tag_health: 'Health', forms_download: 'Download',
    oracao_eyebrow: 'Prayer Wall · Intercessor network',
    oracao_title: 'Prayer requests from the field',
    oracao_lead: 'Every prayer request — from the Monthly Pulse and the Health Assessments — gathered here to share with intercessor groups around the world.',
    oracao_total: 'Requests gathered', oracao_regions: 'Regions', oracao_answered: 'Answered',
    oracao_all: 'All', oracao_share: 'WhatsApp', oracao_db: 'Download database',
    oracao_answered_tag: 'Answered', oracao_empty: 'No prayer requests yet. When teams submit the forms, requests appear here.',
    oracao_footnote: 'TXT to share with groups · CSV and JSON for the intercession database. Requests come from both forms (Monthly Pulse and Health Assessment).',
    oracao_sub_mural: 'Prayer wall', oracao_sub_rede: 'Intercessor network',
    eten_eyebrow: 'Annual report · Resource Circle',
    eten_title: 'ETEN Credits',
    eten_lead: 'ETEN funds most of Shema\u2019s resources. Each year we report how many chapters each project advanced. Each chapter advanced is worth 1 credit — and the credit total corresponds to next cycle\u2019s resources. Only projects on the ETEN list are counted.',
    eten_report_year: 'Report year',
    eten_total_credits: 'Credits this year', eten_credits_note: '1 chapter advanced = 1 credit',
    eten_listed: 'ETEN projects', eten_listed_sub: 'on the funding list',
    eten_advancing: 'Advancing', eten_advancing_sub: 'gained new chapters in',
    eten_report_for: 'Report for', eten_export_csv: 'Download CSV', eten_gen_report: 'Generate report (PDF)',
    eten_col_project: 'Project', eten_col_start: 'Start', eten_col_end: 'End', eten_col_credits: 'Credits',
    eten_total: 'Total', eten_empty: 'No projects marked on the ETEN list. Mark "Language on ETEN list" in each project form.',
    eten_footnote: 'Credits are computed automatically: chapters translated at year-end minus the prior year-end, per ETEN-listed project. Update each project\u2019s progress to reflect in the report.',
    ritmo_eyebrow: 'Cascade of listening',
    ritmo_title: 'The rhythm of the ecosystem',
    ritmo_lead: 'Shema means "listen". Each meeting is a step of that listening — information flows from the field to leadership, and care flows back. Forms feed the meetings; meetings feed the decisions.',
    ritmo_monthly: 'Monthly', ritmo_quarterly: 'Quarterly', ritmo_annual: 'Annual',
    ritmo_all_ecosystem: 'Whole ecosystem',
    ritmo_m1_title: 'Monthly Pulse', ritmo_m1_desc: 'The Language Operations reviews the region\u2019s team pulses each month and decides what to escalate to the quarterly meeting.',
    ritmo_m2_title: 'Field care', ritmo_m2_desc: 'The region\u2019s Language Operations runs the quarterly Health Assessment with each translation team in the region.',
    ritmo_m3_title: 'Regional strategy', ritmo_m3_desc: 'The Global Strategist meets quarterly with each region\u2019s Language Operations and Administrator to align progress, resources and the quarter\u2019s plan.',
    ritmo_m6_title: 'Prayer pulse', ritmo_m6_desc: 'The Intercessor compiles the month\u2019s prayer requests and shares them with the intercessor network.',
    ritmo_m7_title: 'Resource handoff', ritmo_m7_desc: 'The Global Strategist and the Administrator bring the regions\u2019 accumulated financial needs to the Resource Circle each quarter.',
    ritmo_m4_title: 'Governance', ritmo_m4_desc: 'The Global Strategist and Shema leadership review the health of the whole ecosystem and strategic direction.',
    ritmo_m5_title: 'Annual celebration', ritmo_m5_desc: 'Everyone together: year in review, answered prayers, translation milestones delivered.',
    ritmo_role_supervisor: 'Global Strategist', ritmo_role_leadership: 'Shema leadership',
    ritmo_role_teams: 'Translation teams', ritmo_role_everyone: 'Everyone', ritmo_role_resourcecircle: 'Resource Circle',
    ritmo_feeds: 'Fed by:',
    ritmo_feed_pulso: 'Teams\u2019 monthly pulses', ritmo_feed_health: 'Health Assessments (4 dimensions)',
    ritmo_feed_trends: 'Quarter trends + accumulated needs', ritmo_feed_rollup: 'Health roll-up across all regions',
    ritmo_feed_year: 'Year\u2019s milestones and testimonies', ritmo_feed_prayer: 'The month\u2019s prayer requests',
    ritmo_st_done: 'On track', ritmo_st_pending: 'To do', ritmo_st_overdue: 'Overdue', ritmo_st_new: 'To start',
    ritmo_last: 'Last', ritmo_next: 'Next', ritmo_register: 'Log meeting',
    ritmo_done_this: 'Held on', ritmo_undo: 'Undo', ritmo_save: 'Save',
    ritmo_date: 'Date', ritmo_notes: 'Notes', ritmo_notes_ph: 'Decisions, follow-ups (optional)',
    ritmo_readiness: 'Teams that already reported this period', ritmo_reported: 'reported',
    d_facilitator_person: 'Facilitator',
    d_translators: 'Translators', d_reviewers: 'Reviewers', d_partner: 'Partner', d_contact: 'Contact',
    d_objective: 'Project type', d_total: 'Total planned', d_scope: 'Scope',
    d_portion: 'Portion in translation',
    d_start: 'Start', d_deadline: 'Deadline',
    d_p_translated: 'Translated', d_p_community: 'Community-checked', d_p_approved: 'Mentor-approved',
    d_emotional: 'Emotional', d_relational: 'Relational', d_spiritual: 'Spiritual', d_physical: 'Physical',
    d_last_assessment: 'Last assessment', d_assessor: 'Assessed by',
    d_notes: 'Notes', d_prayer: 'Prayer requests', d_pastoral: 'Pastoral intervention',
    d_no_needs: 'No specific needs registered.',
    d_history_toggle: 'Progress history',
    d_history_records: 'records', d_history_record: 'record',
    d_history_initial: '(initial)',
    d_history_translated: 'Translated:', d_history_approved: 'Approved:', d_history_community: 'Community:',
    health_good: 'Good', health_attention: 'Attention', health_critical: 'Critical', health_na: 'N/A',
    vit_vital: 'Vital', vit_vulnerable: 'Vulnerable', vit_threatened: 'Threatened',
    vit_severely: 'Severely threatened', vit_critical: 'Critical situation', vit_extinct: 'Extinct', vit_na: 'Not assessed',
    status_not_started: 'Not started', status_in_progress: 'In progress', status_final: 'Final phase', status_completed: 'Completed',
    status_paused: 'Paused', status_canceled: 'Canceled', status_planned: 'Planned', status_unknown: 'No info',
    stale_uptodate: 'Up to date', stale_attention: 'No news 60+ days', stale_critical: 'Critical 120+ days',
    days_overdue: 'd overdue', days_remaining: 'd left',
    deadline_left: 'In',
    stale_warn_title: 'No recent update.', stale_warn_text: 'No news from the field for',
    stale_crit_title: 'Team out of touch.', stale_crit_text: 'No progress record for',
    days: 'days',
    nav_id: '1 Identification', nav_eq: '2 Team', nav_obj: '3 Objective', nav_prog: '4 Progress',
    nav_health: '5 Health', nav_needs: '6 Needs', nav_notes: '7 Notes',
    f_lang_name: 'Language name', f_lang_code: 'ISO code', f_bridge: 'Bridge language',
    f_vitality: 'Vitality', f_location: 'Country / Region',
    f_location2: 'Additional country / region', placeholder_location2: 'Other country where the language is spoken (optional)',
    f_speakers: 'Speakers (estimated)', f_translation_type: 'Translation type',
    f_sensitive: 'Sensitive country for Bible distribution',
    f_sensitive_hint: 'Check if public exposure could put the team at risk.',
    d_sensitive_tag: 'Sensitive country', sb_sensitive: 'Sensitive country',
    sensitive_yes: 'Sensitive', sensitive_no: 'Open',
    f_financial: 'Funding sources',
    f_facilitators: 'Base / Team', f_ywam: 'YWAM/JOCUM base', f_leader: 'Team leader',
    f_mentor: 'Mentor', f_translators: 'Translators', f_reviewers: 'Technical reviewers',
    f_partner: 'Partner organization', f_contact: 'Contact / Email / WhatsApp',
    f_obj: 'Translation scope', f_total_planned: 'Total planned', f_unit_type: 'Unit',
    f_phases: 'Project phases', f_phases_hint: 'Split the project into periods. Each phase has its own goal and deadline.',
    f_phase_n: 'Phase', f_phase_scope: 'Phase goal (e.g. Gospel of John)', f_phase_add: 'Add phase',
    d_phases: 'Phases',
    f_scope: 'Scope (books, chapters…)',
    f_translated: '1. Translated', f_community: '2. Community-checked',
    f_approved: '3. Mentor-approved', f_start: 'Start date', f_deadline: 'Deadline',
    f_emotional: 'Emotional', f_relational: 'Relational', f_spiritual: 'Spiritual', f_physical: 'Physical',
    f_assessment_date: 'Last assessment date', f_assessor: 'Assessed by',
    f_health_notes: 'Health notes', f_prayer: 'Prayer requests',
    f_pastoral: 'Pastoral intervention needed?', f_pastoral_who: 'Who will do it?',
    f_need_financial: 'Financial support', f_need_training: 'Training', f_need_equipment: 'Equipment',
    need_cat_financial: '💰 Financial', need_cat_training: '🎓 Training', need_cat_equipment: '💻 Equipment',
    need_cat_volunteers: '🤝 Volunteers', need_cat_material: '📚 Teaching material',
    need_cat_security: '🛡️ Security', need_cat_connectivity: '📡 Connectivity',
    need_cat_logistics: '🚗 Transport / Logistics', need_cat_documentation: '📑 Documentation',
    need_urgency_label: 'Urgency',
    need_urgency_low: 'Low', need_urgency_medium: 'Medium', need_urgency_high: 'Urgent',
    need_status_label: 'Status',
    need_status_open: 'Open', need_status_inprogress: 'In progress', need_status_fulfilled: 'Fulfilled',
    need_estimated_value: 'Estimated value',
    need_deadline: 'Deadline',
    need_description: 'Description',
    need_fulfilled_by: 'Fulfilled by',
    need_fulfilled_date: 'Fulfilled date',
    need_prayer_shared: 'Shared in prayer network',
    need_prayer_answered: 'Answered in prayer',
    need_add_item: '+ Add need',
    needs_export: 'Download data',
    need_submitted_by: 'Filled by', need_submitted_at: 'Filled on',
    need_quick_categories: 'Quick categories (with active need)',
    need_items_title: 'Wishlist',
    f_needs_notes: 'General notes',
    f_notes: 'Free notes',
    placeholder_lang: 'E.g. Yanomami',
    placeholder_iso: 'E.g. ymv',
    placeholder_bridge: 'E.g. Portuguese',
    placeholder_location: 'E.g. Roraima, Brazil',
    placeholder_facilitators: 'E.g. North Team',
    placeholder_leader: 'Leader name',
    placeholder_translators: 'Comma-separated',
    progress_tip: 'Number changes are automatically saved to history.',
    sim: 'Yes', nao: 'No',
    unit_books: 'Books', unit_chapters: 'Chapters', unit_verses: 'Verses',
    unit_pages: 'Pages', unit_stories: 'Stories', unit_other: 'Other',
    proj_nt: 'New Testament', proj_ot: 'Old Testament', proj_complete: 'Complete Bible',
    proj_books: 'Specific Books', proj_chapters: 'Chapters', proj_stories: 'Stories',
    proj_jesus: 'Jesus Film', proj_written: 'Written translation', proj_other: 'Other',
    proj_obt: 'OBT', proj_omt: 'OMT', proj_obtomt: 'OBT/OMT', proj_sign: 'Sign Language', proj_ready: 'Ready Vessels',
    fin_seed: 'Seed Company', fin_global: 'Global Partnerships', fin_eten: 'OBT TABLE - ETEN', fin_innov: 'Innovation Lab',
    toast_saved: 'Project saved.', toast_deleted: 'Project removed.',
    toast_exported: 'Data exported.', toast_imported: 'projects imported.',
    toast_field_generated: 'Field form generated — send to the team.',
    toast_field_received: 'Field update applied.',
    toast_field_invalid: 'Invalid update file.',
    toast_obj_required: 'Select at least one project type.',
    confirm_delete: 'Delete this project? This cannot be undone.',
    confirm_import: 'Import will replace current projects. Continue?',
    modal_new: 'New Project', modal_edit: 'Edit Project',
    tweaks_title: 'Variations',
    tweaks_metaphor: 'Visual metaphor',
    tweaks_metaphor_sub: 'How do you want to see the projects today?',
    tweaks_density: 'Density',
    tweaks_accent: 'Accent color',
    tweaks_show_photos: 'Show hero photo',
    field_title: 'Field Form',
    field_form_progress: '📊 Progress',
    field_form_health: '❤️ Team Health',
    field_form_needs: '🤝 Needs',
    field_form_media: '📸 Media & Stories',
    field_form_full: '📋 Full update',
    field_form_choose: 'Send form…',
    field_sub: 'Fill in and download the file to send back to coordination.',
    field_section_progress: 'Progress',
    field_section_needs: 'Needs',
    field_section_pastoral: 'Pastoral Support',
    field_section_notes: 'Notes',
    field_pastoral_question: 'Does the team need pastoral support right now?',
    field_pastoral_details: 'Describe the situation (optional)',
    field_prayer_label: 'Prayer requests',
    field_label_project: 'Project:', field_label_team: 'Team:', field_label_mentor: 'Mentor:',
    field_label_date: 'Date:',
    field_your_name: 'Your name (who is reporting)',
    field_save_btn: 'Download update',
    field_saved: 'Update generated. Send the file to your coordinator.',
    field_instructions: 'How to use:',
    field_instr_1: 'Update the numbers below to reflect real progress since the last check.',
    field_instr_2: 'Mark current needs (financial, training, equipment).',
    field_instr_3: 'Add notes, prayer requests or recent context.',
    field_instr_4: 'Click "Download update" and email the .json file to coordination.',
  }
};

// ---------- SAMPLE DATA ----------
// Real Brazilian indigenous languages + a few global YWAM contexts.
// Names of facilitators/mentors are drawn from the YWAM participant list.
// Today (for stale calc reference): 2026-05-14

function daysAgo(n) {
  const d = new Date('2026-05-14');
  d.setDate(d.getDate() - n);
  return d.toISOString().split('T')[0];
}
function daysFromNow(n) {
  const d = new Date('2026-05-14');
  d.setDate(d.getDate() + n);
  return d.toISOString().split('T')[0];
}

// SAMPLE_PROJECTS comes from projects.js (loaded as window.SHEMA_PROJECTS)

// ---------- DERIVED HELPERS ----------
function getProgress(p) {
  return p.totalUnits > 0 ? (p.translatedUnits / p.totalUnits) * 100 : 0;
}
function getProjectStatus(p) {
  // Prefer explicit status field from CSV import
  if (p.status === 'em-andamento' || p.status === 'cancelado' || p.status === 'pausado' || p.status === 'planejado' || p.status === 'concluido' || p.status === 'desconhecido') {
    return p.status;
  }
  const prog = getProgress(p);
  if (prog === 0) return 'nao-iniciado';
  if (prog === 100) return 'concluido';
  if (prog >= 75) return 'final';
  return 'em-andamento';
}
function getOverallHealth(p) {
  const vals = [p.healthEmotional, p.healthRelational, p.healthSpiritual, p.healthPhysical].filter(Boolean);
  if (vals.length === 0) return 'na';
  if (vals.some(v => v === 'critica')) return 'critica';
  if (vals.some(v => v === 'atencao')) return 'atencao';
  return 'boa';
}
function healthScore(p) {
  const m = { boa: 3, atencao: 2, critica: 1, '': 0 };
  return (m[p.healthEmotional]||0) + (m[p.healthRelational]||0) + (m[p.healthSpiritual]||0) + (m[p.healthPhysical]||0);
}
function getLastProgressUpdate(p) {
  if (p.progressHistory && p.progressHistory.length) return p.progressHistory[p.progressHistory.length - 1].date;
  return p.startDate || null;
}
function getDaysSinceUpdate(p) {
  const date = getLastProgressUpdate(p);
  if (!date) return null;
  const last = new Date(date + 'T00:00:00');
  const today = new Date('2026-05-14');
  return Math.floor((today - last) / (1000 * 60 * 60 * 24));
}
function getStaleStatus(p) {
  const st = getProjectStatus(p);
  // Concluded / canceled / planned projects don't count as 'stale'
  if (st === 'concluido' || st === 'cancelado' || st === 'planejado' || st === 'desconhecido') return null;
  const days = getDaysSinceUpdate(p);
  if (days === null) return null;
  if (days >= 120) return 'critico';
  if (days >= 60) return 'atencao';
  return 'em-dia';
}
function getDeadlineInfo(deadline) {
  if (!deadline) return { cls: '', days: null };
  const d = new Date(deadline);
  const now = new Date('2026-05-14');
  const days = Math.ceil((d - now) / (1000 * 60 * 60 * 24));
  if (days < 0) return { cls: 'overdue', days };
  if (days < 90) return { cls: 'soon', days };
  return { cls: 'ok', days };
}
function getPriority(p) {
  const h = getOverallHealth(p);
  const s = getStaleStatus(p);
  const st = getProjectStatus(p);
  if (st === 'cancelado') return 'canceled';
  if (st === 'pausado') return 'paused';
  if (h === 'critica' || s === 'critico') return 'critical';
  if (h === 'atencao' || s === 'atencao') return 'warning';
  if (st === 'concluido') return 'completed';
  if (st === 'planejado') return 'planned';
  if (st === 'desconhecido') return 'unknown';
  return 'default';
}
function formatDate(ds, locale='pt-BR') {
  if (!ds) return '—';
  return new Date(ds + 'T00:00:00').toLocaleDateString(locale, { day: '2-digit', month: 'short', year: 'numeric' });
}
function escapeHtml(str) {
  if (str === null || str === undefined) return '';
  return String(str).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}

// ---------- 66 Books of the Bible ----------
const BIBLE_BOOKS = [
  // Old Testament
  { id: 'gen', name: 'Gênesis', en: 'Genesis', chapters: 50, ot: true },
  { id: 'exo', name: 'Êxodo', en: 'Exodus', chapters: 40, ot: true },
  { id: 'lev', name: 'Levítico', en: 'Leviticus', chapters: 27, ot: true },
  { id: 'num', name: 'Números', en: 'Numbers', chapters: 36, ot: true },
  { id: 'deu', name: 'Deuteronômio', en: 'Deuteronomy', chapters: 34, ot: true },
  { id: 'jos', name: 'Josué', en: 'Joshua', chapters: 24, ot: true },
  { id: 'jdg', name: 'Juízes', en: 'Judges', chapters: 21, ot: true },
  { id: 'rut', name: 'Rute', en: 'Ruth', chapters: 4, ot: true },
  { id: '1sa', name: '1 Samuel', en: '1 Samuel', chapters: 31, ot: true },
  { id: '2sa', name: '2 Samuel', en: '2 Samuel', chapters: 24, ot: true },
  { id: '1ki', name: '1 Reis', en: '1 Kings', chapters: 22, ot: true },
  { id: '2ki', name: '2 Reis', en: '2 Kings', chapters: 25, ot: true },
  { id: '1ch', name: '1 Crônicas', en: '1 Chronicles', chapters: 29, ot: true },
  { id: '2ch', name: '2 Crônicas', en: '2 Chronicles', chapters: 36, ot: true },
  { id: 'ezr', name: 'Esdras', en: 'Ezra', chapters: 10, ot: true },
  { id: 'neh', name: 'Neemias', en: 'Nehemiah', chapters: 13, ot: true },
  { id: 'est', name: 'Ester', en: 'Esther', chapters: 10, ot: true },
  { id: 'job', name: 'Jó', en: 'Job', chapters: 42, ot: true },
  { id: 'psa', name: 'Salmos', en: 'Psalms', chapters: 150, ot: true },
  { id: 'pro', name: 'Provérbios', en: 'Proverbs', chapters: 31, ot: true },
  { id: 'ecc', name: 'Eclesiastes', en: 'Ecclesiastes', chapters: 12, ot: true },
  { id: 'sng', name: 'Cantares', en: 'Song of Solomon', chapters: 8, ot: true },
  { id: 'isa', name: 'Isaías', en: 'Isaiah', chapters: 66, ot: true },
  { id: 'jer', name: 'Jeremias', en: 'Jeremiah', chapters: 52, ot: true },
  { id: 'lam', name: 'Lamentações', en: 'Lamentations', chapters: 5, ot: true },
  { id: 'ezk', name: 'Ezequiel', en: 'Ezekiel', chapters: 48, ot: true },
  { id: 'dan', name: 'Daniel', en: 'Daniel', chapters: 12, ot: true },
  { id: 'hos', name: 'Oseias', en: 'Hosea', chapters: 14, ot: true },
  { id: 'jol', name: 'Joel', en: 'Joel', chapters: 3, ot: true },
  { id: 'amo', name: 'Amós', en: 'Amos', chapters: 9, ot: true },
  { id: 'oba', name: 'Obadias', en: 'Obadiah', chapters: 1, ot: true },
  { id: 'jon', name: 'Jonas', en: 'Jonah', chapters: 4, ot: true },
  { id: 'mic', name: 'Miqueias', en: 'Micah', chapters: 7, ot: true },
  { id: 'nam', name: 'Naum', en: 'Nahum', chapters: 3, ot: true },
  { id: 'hab', name: 'Habacuque', en: 'Habakkuk', chapters: 3, ot: true },
  { id: 'zep', name: 'Sofonias', en: 'Zephaniah', chapters: 3, ot: true },
  { id: 'hag', name: 'Ageu', en: 'Haggai', chapters: 2, ot: true },
  { id: 'zec', name: 'Zacarias', en: 'Zechariah', chapters: 14, ot: true },
  { id: 'mal', name: 'Malaquias', en: 'Malachi', chapters: 4, ot: true },
  // New Testament
  { id: 'mat', name: 'Mateus', en: 'Matthew', chapters: 28, ot: false },
  { id: 'mrk', name: 'Marcos', en: 'Mark', chapters: 16, ot: false },
  { id: 'luk', name: 'Lucas', en: 'Luke', chapters: 24, ot: false },
  { id: 'jhn', name: 'João', en: 'John', chapters: 21, ot: false },
  { id: 'act', name: 'Atos', en: 'Acts', chapters: 28, ot: false },
  { id: 'rom', name: 'Romanos', en: 'Romans', chapters: 16, ot: false },
  { id: '1co', name: '1 Coríntios', en: '1 Corinthians', chapters: 16, ot: false },
  { id: '2co', name: '2 Coríntios', en: '2 Corinthians', chapters: 13, ot: false },
  { id: 'gal', name: 'Gálatas', en: 'Galatians', chapters: 6, ot: false },
  { id: 'eph', name: 'Efésios', en: 'Ephesians', chapters: 6, ot: false },
  { id: 'php', name: 'Filipenses', en: 'Philippians', chapters: 4, ot: false },
  { id: 'col', name: 'Colossenses', en: 'Colossians', chapters: 4, ot: false },
  { id: '1th', name: '1 Tessalonicenses', en: '1 Thessalonians', chapters: 5, ot: false },
  { id: '2th', name: '2 Tessalonicenses', en: '2 Thessalonians', chapters: 3, ot: false },
  { id: '1ti', name: '1 Timóteo', en: '1 Timothy', chapters: 6, ot: false },
  { id: '2ti', name: '2 Timóteo', en: '2 Timothy', chapters: 4, ot: false },
  { id: 'tit', name: 'Tito', en: 'Titus', chapters: 3, ot: false },
  { id: 'phm', name: 'Filemom', en: 'Philemon', chapters: 1, ot: false },
  { id: 'heb', name: 'Hebreus', en: 'Hebrews', chapters: 13, ot: false },
  { id: 'jas', name: 'Tiago', en: 'James', chapters: 5, ot: false },
  { id: '1pe', name: '1 Pedro', en: '1 Peter', chapters: 5, ot: false },
  { id: '2pe', name: '2 Pedro', en: '2 Peter', chapters: 3, ot: false },
  { id: '1jn', name: '1 João', en: '1 John', chapters: 5, ot: false },
  { id: '2jn', name: '2 João', en: '2 John', chapters: 1, ot: false },
  { id: '3jn', name: '3 João', en: '3 John', chapters: 1, ot: false },
  { id: 'jud', name: 'Judas', en: 'Jude', chapters: 1, ot: false },
  { id: 'rev', name: 'Apocalipse', en: 'Revelation', chapters: 22, ot: false },
];

// Aggregate book/story progress arrays into legacy totals
function rollUpProgress(p) {
  const items = [...(p.bookProgress || []), ...(p.storyProgress || []), ...(p.otherProgress || [])];
  if (items.length === 0) return null;
  let tr = 0, co = 0, ap = 0, total = 0;
  items.forEach(it => {
    total += +it.chapters || 0;
    tr += +it.translated || 0;
    co += +it.communityChecked || 0;
    ap += +it.mentorApproved || 0;
  });
  return { translated: tr, community: co, approved: ap, total };
}

window.SHEMA = {
  I18N, BIBLE_BOOKS, rollUpProgress,
  get SAMPLE_PROJECTS() { return window.SHEMA_PROJECTS || []; },
  getProgress, getProjectStatus, getOverallHealth, healthScore,
  getLastProgressUpdate, getDaysSinceUpdate, getStaleStatus,
  getDeadlineInfo, getPriority, formatDate, escapeHtml,
  daysAgo, daysFromNow,
};
